### ISSUE TITLE
关于2.1.2 基于成词模式，想问下具体是怎么做规则的，做了哪些规则？

### ISSUE THREAD

**Issue by jiaruncao** [Pzoom522/BDCI#3]
希望能具体描述一下

**Comment by Pzoom522** [comment]
我们的规则包括两类：

- 关键词型。这个的主要思路是在[2.1.1](https://github.com/Pzoom522/BDCI#211-%E5%9F%BA%E4%BA%8E%E5%91%BD%E5%90%8D%E5%AE%9E%E4%BD%93%E8%AF%86%E5%88%ABner)基础上，进行分词并统计词频，从而发现对应实体的关键词。相关代码可以参考[“企业类”](https://github.com/Pzoom522/BDCI/blob/master/tool%20chain/simple_pos_ne.py#L1)和[“政府类”](https://github.com/Pzoom522/BDCI/blob/master/tool%20chain/simple_pos_ne.py#L11)

- 句法分析型。我们通过统计常见机构实体短句和词组，构造了面向企业的规则，可以参考[相关代码](https://github.com/Pzoom522/BDCI/blob/master/tool%20chain/pos2ner.py)。由于关键词型对“政府类”覆盖较好，这个方法主要用来补全“企业类”实体，对效果提升很大。

欢迎随时交流！
